#### **Numpy**

Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures. In this lesson, we will cover the basics of numpy, focusing on arrays and vectorized operations.

+ install numpy first
  + for conda ```conda install numpy```
  + or in jupyter notebook ```!pip install numpy```

In [69]:
import numpy as np

**create array using numpy**

+ 1D array

In [70]:
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [71]:
arr1 = np.array(list(range(1,6)))
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


+ shape of the array

In [72]:
print(arr1.shape)

(5,)


+ reshape to 2 dim array

In [73]:
arr2 = np.array([1,2,3,4,5])
arr2 = arr2.reshape(1,5) # 1 row 5 col
print(arr2)

[[1 2 3 4 5]]


In [74]:
print(arr2.ndim)

2


+ one thing remember while reshaping the element must equally distribute in every row

In [75]:
arr2 = np.array(list(range(10)))
print(arr2)

arr2 = arr2.reshape(2,5) # 2 row 5 col
print(arr2)

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [76]:
print(f"dimension: {arr2.ndim}")

dimension: 2


In [79]:
# creating 2d array using manually 
arr2 = np.array(
    [
        list(range(5)),
        list(range(5,10))
    ]
)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [80]:
print(arr2.ndim)

2


+ ```arange(start, stop, step)```

In [81]:
arr3 = np.arange(0,10,2)
print(arr3)

[0 2 4 6 8]


In [83]:
arr3 = arr3.reshape(5,1)
print(arr3)
print(f"dimension: {arr3.ndim}")

[[0]
 [2]
 [4]
 [6]
 [8]]
dimension: 2


---
+ ```ones((row,col))```

In [ ]:
ones = np.ones(3) # one row 3 col
print(ones)

[1. 1. 1.]


In [ ]:
ones = np.ones((4,4)) # 4 row 4 col
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


---
+ identity matrix
  

In [91]:
identity = np.eye(4)
print(identity)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


---
+ zeros

In [92]:
zeros = np.zeros(5)
print(zeros)

[0. 0. 0. 0. 0.]


In [93]:
zeros = np.zeros((5,5))
print(zeros)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


---
+ attributes of numpy

In [99]:
arr = np.array(
    [
        np.arange(5),
        np.arange(5,10)
    ]
)

print(f"array: {arr}")
print("--"*15)
print(f"shape: {arr.shape}")
print(f"dimension: {arr.ndim}")
print(f"size: {arr.size}")
print(f"data type: {arr.dtype}")
print(f"item size (in bytes): {arr.itemsize}")



array: [[0 1 2 3 4]
 [5 6 7 8 9]]
------------------------------
shape: (2, 5)
dimension: 2
size: 10
data type: int64
item size (in bytes): 8


---
+ numpy vectorized operation

In [106]:
arr1 = np.arange(1,6)
arr2 = np.arange(10,51,10)

print(arr1)
print(arr2)
print("--"*20)

# element wise operation
print(f"addition: {arr1 + arr2}")
print(f"subtraction: {arr1 - arr2}")
print(f"multiplication: {arr1 * arr2}")
print(f"division: {arr1 / arr2}")
print(f"modulus: {arr1 % arr2}")

[1 2 3 4 5]
[10 20 30 40 50]
----------------------------------------
addition: [11 22 33 44 55]
subtraction: [ -9 -18 -27 -36 -45]
multiplication: [ 10  40  90 160 250]
division: [0.1 0.1 0.1 0.1 0.1]
modulus: [1 2 3 4 5]


---
+ universal function

In [111]:
arr = np.arange(2,7)

print(arr)
print(f"sqrt: {np.sqrt(arr)}")
print(f"exponential: {np.exp(arr)}")
print(f"sin: {np.sin(arr)}")
print(f"natural log: {np.log(arr)}")
print(f"log10: {np.log10(arr)}")

[2 3 4 5 6]
sqrt: [1.41421356 1.73205081 2.         2.23606798 2.44948974]
exponential: [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
sin: [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
natural log: [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]
log10: [0.30103    0.47712125 0.60205999 0.69897    0.77815125]


---
+ array slicing and indexing

In [113]:
arr = np.array(
    [
        np.arange(1,5),
        np.arange(5,9),
        np.arange(9,13)
    ]
)
print(f"array: \n{arr}")

array: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [115]:
arr[0]

array([1, 2, 3, 4])

In [117]:
print(arr[0][0])

1


+ with the help of array slicing

In [122]:
# 7 8
# 11 12

print(arr[1:, 2:])

[[ 7  8]
 [11 12]]


In [ ]:
# want to extract 
# 3 4
# 7 8
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [124]:
print(arr[0:2, 2:])

[[3 4]
 [7 8]]


In [145]:
# diagonal element only
row = arr.shape[0]
col = arr.shape[1]

print(f"row: {row}")
print(f"col: {col}")

print("diagonal elements: ", end="")
for i in range(row):
    print(arr[i,i], end=" ")


row: 3
col: 4
diagonal elements: 1 6 11 

In [148]:
print(arr)
# extract 
# 2 3
# 6 7
# 10 11
print("--"*20)
print(arr[0:, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------------------------------
[[ 2  3]
 [ 6  7]
 [10 11]]


---
+ modify array elements

In [149]:
print(arr)
print("--"*20)

arr[0][0] = 500
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
----------------------------------------
[[500   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [150]:
arr[1:] = 300
print(arr)

[[500   2   3   4]
 [300 300 300 300]
 [300 300 300 300]]


---
+ **statistical concepts** 
  + Normalization : $$Z = \frac{X - \mu}{\sigma}$$


In [151]:
data = np.arange(1,6)

mean = np.mean(data)
std_dev = np.std(data)

normalized_data = (data - mean) / std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [153]:
data = np.arange(1, 11)

print(f"data: {data}")

mean = np.mean(data)
median = np.median(data)
std_dev = np.std(data)
variance = np.var(data)

print(f"mean: {mean}")
print(f"median: {median}")
print(f"standard deviation: {std_dev}")
print(f"variance: {variance}")


data: [ 1  2  3  4  5  6  7  8  9 10]
mean: 5.5
median: 5.5
standard deviation: 2.8722813232690143
variance: 8.25


---
+ logical operation

In [158]:
data = np.arange(1, 11)

print(data>5)
print(data[data>5])

print(data[(data>=2) & (data%2==0)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[ 2  4  6  8 10]
